spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cutemeet_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: cutemeetv@gmail.com
    password: hois vqmn lnrs qikc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
